export const GET_MEDIA_FILES = "GET_MEDIA_FILES";
export const GET_MEDIA_FILES_SUCCESS = "GET_MEDIA_FILES_SUCCESS";
export const GET_MEDIA_FILES_FAILURE = "GET_MEDIA_FILES_FAILURE";

export const MEDIA_FILES_LOADING = "MEDIA_FILES_LOADING";
export const MEDIA_FILES_LOADING_SUCCESS = "MEDIA_FILES_LOADING_SUCCESS";

